language: go

go:
  - 1.7.6
  - 1.8.x
  - master

before_script:
  - &nc -l localhost 1234
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
